FS Cloud refactor
terraform-ibm-modules/terraform-ibm-cos pull request #448
Opened 2023-10-09 15:12 UTC by daniel-butler-irl

### Description

Refactor of FS Cloud profile to handle multiple buckets and CBR rules. Added tests for CBRs

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

##### Release notes content
- refactor of fscloud submodule to support multiple buckets
- refactor includes support for all existing bucket configurations
- fix for deploying CBRs with enforcement mode set to enabled, previously this would fail
- added unit tests for CBRs in fscloud submodule to validate they are correctly configured and applied
- added additional outputs including CBR rule IDs which can be useful for testing

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-10-09 15:12 UTC, daniel-butler-irl commented
/run pipeline

2023-10-09 15:21 UTC, daniel-butler-irl commented
/run pipeline

2023-10-09 15:33 UTC, daniel-butler-irl commented
/run pipeline

2023-10-09 16:01 UTC, daniel-butler-irl commented
/run pipeline

2023-10-09 16:28 UTC, daniel-butler-irl commented
/run pipeline

2023-10-11 08:13 UTC, daniel-butler-irl commented
/run pipeline

2023-10-11 09:19 UTC, daniel-butler-irl commented
/run pipeline

2023-10-11 14:23 UTC, shemau requested changes
Some changes to variable/output names to make them more consistent.

2023-10-11 14:23 UTC, shemau commented on modules/buckets/outputs.tf
> +output "cbr_rule_ids" {
These would read better as `cbr_rules` and `cbs_rule_ids`

2023-10-11 14:29 UTC, daniel-butler-irl commented on modules/fscloud/version.tf
> -  }
I think you are right and I should have added `# tflint-ignore: terraform_unused_required_providers`

2023-10-11 14:36 UTC, daniel-butler-irl commented on modules/fscloud/main.tf
> +module "instance_cbr_rule" {
I think I need to check this. I thought you could only have one rule per instance. But you can have multiple zones. I could be wrong, checking.....

2023-10-11 15:03 UTC, daniel-butler-irl commented on modules/fscloud/main.tf
> +module "instance_cbr_rule" {
I was wrong, I'll update now

2023-10-11 15:49 UTC, daniel-butler-irl commented
/run pipeline

2023-10-11 16:09 UTC, daniel-butler-irl commented
/run pipeline

2023-10-12 16:26 UTC, shemau approved these changes
LGTM

2023-10-13 07:28 UTC, ocofaigh commented
I'm thinking this is a major release due to the fact the fscloud submodule has been refactored and has no backward compatibility. 
Can you please also include release notes in the PR description.

2023-10-13 08:14 UTC, merged

2023-10-13 08:16 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 7.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v7.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: