onboard to module catalog
terraform-ibm-modules/terraform-ibm-cos pull request #451
Opened 2023-11-09 14:02 UTC by ocofaigh

### Description

onboard to module catalog

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-11-09 15:08 UTC, SirSpidey requested changes
see what you think

2023-11-09 15:08 UTC, SirSpidey commented on ibm_catalog.json
> +                    "description": "Supports creating context based restriction rules for both instance and buckets"
```suggestion
                    "title": "Create Object Storage instance",
                    "description": "Create an IBM Cloud Object Storage instance."
                },
                {
                    "title": "Create Object Storage buckets",
                    "description": "Create both cross-regional and regional Object Storage buckets."
                },
                {
                    "title": "Create HMAC key",
                    "description": "Create an HMAC key for the Object Storage instance."
                },
                {
                    "title": "Attach access tags",
                    "description": "Attach access tags to the Object Storage instance."
                },
                {
                    "title": "Bucket retention",
                    "description": "Configure bucket retention."
                },
                {
                    "title": "Object versioning",
                    "description": "Supports enabling object versioning to keep multiple versions of an object in a bucket."
                },
                {
                    "title": "Archiving",
                    "description": "Add archive policies on the bucket."
                },
                {
                    "title": "Activity Tracking",
                    "description": "Integrate Activity Tracker events."
                },
                {
                    "title": "Monitoring",
                    "description": "Provision IBM Cloud Monitoring on Object Storage data."
                },
                {
                    "title": "KMS encryption",
                    "description": "Supports key management encryption (BYOK and KYOK), including service-to-service authorization policies with KMS."
                },
                {
                    "title": "CBR",
                    "description": "Create context-based restriction (CBR) rules for both instance and buckets."
```

2023-11-09 15:08 UTC, SirSpidey commented on ibm_catalog.json
> +                    "label": "Complete (multiple COS Buckets with retention, encryption, tracking and monitoring enabled)",
```suggestion
                    "label": "Complete (multiple Object Storage buckets with retention, encryption, tracking, and monitoring)",
```

2023-11-09 15:08 UTC, SirSpidey commented on ibm_catalog.json
> +                    "label": "Financial Services Cloud",
```suggestion
                    "label": "IBM Cloud Framework for Financial Services compliant",
```

2023-11-09 15:08 UTC, SirSpidey commented on ibm_catalog.json
> +                    "label": "COS Bucket with One Rate Plan",
```suggestion
                    "label": "Object Storage bucket with a One Rate plan",
```

2023-11-09 15:08 UTC, SirSpidey commented on ibm_catalog.json
> +                    "label": "COS Bucket Replication",
```suggestion
                    "label": "Object Storage bucket with replication",
```

2023-11-09 15:14 UTC, ocofaigh commented on ibm_catalog.json
> +            "tags": [
@kbiegert can you confirm?

2023-11-09 15:21 UTC, kbiegert commented on ibm_catalog.json
> +            "tags": [
These should be the keywords that you can use on the search page, https://cloud.ibm.com/catalog

2023-11-09 15:24 UTC, SirSpidey commented on ibm_catalog.json
> +            "tags": [
@kbiegert what about tags?

2023-11-09 15:27 UTC, kbiegert commented on ibm_catalog.json
> +                "cos",
Yes, as a search term

2023-11-09 15:27 UTC, ocofaigh commented on ibm_catalog.json
> +            "offering_icon_url": "https://raw.githubusercontent.com/terraform-ibm-modules/terraform-ibm-cos/main/docs/cos_icon.svg",
moved to images directory

2023-11-09 15:45 UTC, kbiegert commented on ibm_catalog.json
> +            "tags": [
I believe tags determine the industry setting

2023-11-09 16:30 UTC, SirSpidey approved these changes
I don't want to hold this up. 

Separately, I think we need some more guidance about values: tags, keywords, product names, features... We might be able to rely on the  cloud docs catalog writers to provide that for both us and 3rd party users.

2023-11-09 16:34 UTC, SirSpidey commented
@ocofaigh For features, you might be able to clean up here and now: 

**use the correct singular or plural in features.** 

For example, we have `Create Object Storage instance` (single) `Create Object Storage buckets` (plural). For these and all the features, it should be plural if you can provision more than one. I don't know the code well enough to get that correct.

2023-11-09 16:36 UTC, ocofaigh commented
@SirSpidey The root level module supports optionally creating 1 instance and 1 bucket. The buckets submodule however supports creating multiple buckets. The problem is the module catalog does not expose submodules currently, so I think Ill update the feature to be single rather than plural for now

2023-11-09 16:40 UTC, ocofaigh commented
/run pipeline

2023-11-09 16:41 UTC, ocofaigh commented
Thanks @SirSpidey - can I get another approval off you here so I can merge?

2023-11-09 16:42 UTC, ocofaigh commented
/run pipeline

2023-11-09 17:47 UTC, SirSpidey approved these changes
👍

2023-11-10 08:03 UTC, merged

2023-11-10 08:05 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 7.0.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v7.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: