Examples documentation cleanup
terraform-ibm-modules/terraform-ibm-cos pull request #459
Opened 2023-11-15 10:20 UTC by ocofaigh

### Description

Examples documentation cleanup

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-11-15 14:53 UTC, SirSpidey requested changes
See whether these suggestions work. A lot of it is expanding abbreviations and using official product names. We'll want to use the same language across all the examples.

2023-11-15 15:15 UTC, ocofaigh commented on examples/replication/README.md
> +- A Sysdig and Activity Tracker instance (if existing one is not passed in) in the given resource group and region.
The example only supports passing in existing AT instance (not sysdig) - Can you suggest a reword for that @SirSpidey ?

2023-11-15 15:31 UTC, ocofaigh commented on examples/replication/README.md
> +- A Cloud Object Storage instance in the given resource group and region.
actually these bullet points were not supposed to here :) removed now

2023-11-15 15:58 UTC, ocofaigh commented on examples/replication/README.md
> +- A Sysdig and Activity Tracker instance (if existing one is not passed in) in the given resource group and region.
Going to split into 2 separate bullet points

2023-11-15 15:58 UTC, ocofaigh commented on examples/replication/README.md
> +- A Sysdig and Activity Tracker instance (if existing one is not passed in) in the given resource group and region.
Going to split into 2 separate bullet points

2023-11-15 16:06 UTC, SirSpidey approved these changes
let's go and see how it looks now...

2023-11-15 16:27 UTC, ocofaigh commented
/run pipeline

2023-11-15 18:12 UTC, ocofaigh commented
Holding off on merge until https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/460 is merged into this, and we finalise a diagram

2023-11-16 16:45 UTC, SirSpidey approved these changes
Approving because I think we've nailed the various updates for now.

2023-11-16 19:06 UTC, ocofaigh commented
/run pipeline

2023-11-16 19:11 UTC, SirSpidey approved these changes
:shipit:

2023-11-16 19:25 UTC, merged

2023-11-16 19:27 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 7.0.4 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-cos/releases/tag/v7.0.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: