Examples code updated with changes as requested (default values removed, use of variables restricted to only least, local values used wherever applicable, provider with lowest and one latest version defined, test/plan/apply verified)
terraform-ibm-modules/terraform-ibm-cos pull request #521
Opened 2024-01-29 10:17 UTC by marifse

### Description

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-01-31 22:09 UTC, ocofaigh requested changes
Left some comments. Have you set up your local dev environment yet using steps at https://terraform-ibm-modules.github.io/documentation/#/local-dev-setup?id=local-development-setup ? Please do this and run `pre-commit run --all-files` as I think some hooks are going to update some of the formatting in your PR. If so, ensure to commit the changes.

2024-01-31 22:09 UTC, ocofaigh commented on examples/advanced/pre_test.go
> +}
As mentioned in previous PR, all tests need to be in pr_test.go, or other_test.go which are both in the tests folder. We already do `InitAndApply` tests in there, but perhaps extra assertions could be added like you have here

2024-01-31 22:09 UTC, ocofaigh commented on examples/advanced/variables.tf
> -  default     = "public"
please add this back

2024-01-31 22:09 UTC, ocofaigh commented on examples/advanced/variables.tf
> -  default     = null
please add this back. if `null` is passed, the example will create a new AT instance

2024-01-31 22:09 UTC, ocofaigh commented on examples/fscloud/variables.tf
> -  default     = null
please add this back. if `null` is passed, the example will create a new AT instance

2024-01-31 22:09 UTC, ocofaigh commented on examples/one-rate-plan/version.tf
> +      version = "1.60.0"
please change this back. As per code comment above, this example should lock into the lowest version that provider supports, which in this case is 1.56.1

2024-01-31 23:03 UTC, ocofaigh requested changes
Please also be aware that in every example, you will find a `catalogValidationValues.json.template`. This is used by an internal pipeline for validating the example, so since you are now updating examples variables.tf files with to make some variables required, please ensure this file is also updated.

2024-02-02 13:00 UTC, marifse commented
> Left some comments. Have you set up your local dev environment yet using steps at https://terraform-ibm-modules.github.io/documentation/#/local-dev-setup?id=local-development-setup ? Please do this and run `pre-commit run --all-files` as I think some hooks are going to update some of the formatting in your PR. If so, ensure to commit the changes.

@ocofaigh yes i have setup the local enviroment and tested running pre-commit run --all-files, and results are all passed.

2024-02-02 16:34 UTC, ocofaigh commented
@marifse thanks, I still dont see any updated to `catalogValidationValues.json.template` ?

2024-02-03 19:47 UTC, marifse commented
> @marifse thanks, I still dont see any updated to `catalogValidationValues.json.template` ?

I did not add any new variable in this module examples, though even if i remove the default values do i need to put those variables into catalogValidationValues.json.template file with their hard coded values? I will appreciate your help, as this is the first module on which I am working.

Another thing, on project description i got the instructions to use the one least available provider and one latest available provider in range defined in module as 1.56 and 2.0, while the 1.56.1 is being used in two or three examples, though there is not any example with only latest one 2.0 but two fscloud and advanced examples are with the range defined as >= 1.56.1, < 2.0.0?

2024-02-04 12:39 UTC, ocofaigh commented
@marifse If you remove a default value from a variable, it becomes a required variable, so you would then need to update the `catalogValidationValues.json.template` files with a value for the variable, however I just checked and it seems only `prefix` and `region` are being made required, and we already pass values in for them in the json template files, so actually there is no action required here. 

The requirement for testing provider versions is that we need to ensure at least 1 example is testing the lowest version defined the the range, and at least 1 testing whatever the latest version is. So in this case, the supported provider range is `1.56.1, <2.00` which means we would want at least 1 example locked into `1.56.1`, and at least 1 example that will always use the current latest version. To achieve that, you would use `>=1.56.1`.

Generally you will need to lock the most basic example into the lowest supported provider version because some of the more complex example may have dependant module that actually require later provider versions.

2024-02-04 12:40 UTC, ocofaigh commented
/run pipeline

2024-02-04 12:51 UTC, ocofaigh commented
@marifse The pre-commit hooks are failing in the pipeline? Are you sure they all pass locally for you? Ensure you set up your local dev environment using steps at https://terraform-ibm-modules.github.io/documentation/#/local-dev-setup?id=local-development-setup and then run `pre-commit run --all-files`.

2024-02-04 18:23 UTC, closed without merging