refactor: added additional prefix validation
terraform-ibm-modules/terraform-ibm-cos pull request #776
Opened 2024-11-14 19:02 UTC by kierramarie

### Description

Added additional prefix validation to check more than length.

 GIT Issue: https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/770

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-14 19:17 UTC, kierramarie commented
/run pipeline

2024-11-14 19:44 UTC, kierramarie commented
/run pipeline

2024-11-14 20:26 UTC, kierramarie commented
/run pipeline

2024-11-15 15:05 UTC, kierramarie commented
/run pipeline

2024-11-15 15:20 UTC, kierramarie commented
/run pipeline

2024-11-20 04:49 UTC, alex-reiff approved these changes

2024-12-09 17:08 UTC, kierramarie commented
/run pipeline

2024-12-11 16:43 UTC, jor2 approved these changes

2024-12-12 16:03 UTC, shemau requested changes

2024-12-12 16:03 UTC, shemau commented on solutions/instance/variables.tf
> +    condition     = can(regex("^([a-z]|[a-z][-a-z0-9]*[a-z0-9])$", coalesce(var.prefix, "cos"))) && length(coalesce(var.prefix, "cos")) <= 16
Very brief discussion in the standup today. Decided this should be a request changes response.

2025-01-06 21:01 UTC, kierramarie commented
/run pipeline

2025-01-06 21:06 UTC, kierramarie commented
/run pipeline

2025-01-06 21:59 UTC, kierramarie commented
/run pipeline

2025-01-21 21:05 UTC, kierramarie commented
/run pipeline

2025-01-21 21:33 UTC, kierramarie commented
/run pipeline

2025-02-05 19:16 UTC, kierramarie commented
/run pipeline

2025-02-10 16:40 UTC, kierramarie commented
/run pipeline

2025-02-11 21:54 UTC, shemau submitted a review, later dismissed
LGTM.

We will need to revisit the order of the IBM catalog JSON later, so that related keys can be adjacent and appear next to each other in the tile.

2025-02-12 14:06 UTC, ocofaigh requested changes
@kierramarie Can you change the format of the json so that its displays pretty format so its consistent with all our other json files?

2025-02-12 14:07 UTC, ocofaigh commented on solutions/instance/variables.tf
> +    error_message = "Prefix must begin with a lowercase letter, contain only lowercase letters, numbers, and - characters. Prefixes must end with a lowercase letter or number and be 16 or fewer chara
The instance variation doesn't create a bucket. So are you enforcing this validation for a COS instance?

2025-02-12 14:09 UTC, ocofaigh requested changes
Validation is required in:
- root level module
- fscloud submodule
- buckets submodule
- the 2 buckets DAs (not the instance DA)

2025-02-12 18:35 UTC, kierramarie commented
@ocofaigh the instance DA is the only one with the prefix variable. It is missing from everything else as far as I can see.

2025-02-17 12:30 UTC, shemau commented on solutions/instance/variables.tf
> +    error_message = "Prefix must begin with a lowercase letter, contain only lowercase letters, numbers, and - characters. Prefixes must end with a lowercase letter or number and be 16 or fewer chara
Yes. In a project/stacks implementation the prefix is done at the top (project) level. My interpretation of what I was told was that prefix had to be enforced (validated) everywhere to avoid the scenario of having many DAs deployed before encountering an error.

2025-02-17 16:59 UTC, ocofaigh commented on solutions/instance/variables.tf
> +    error_message = "Prefix must begin with a lowercase letter, contain only lowercase letters, numbers, and - characters. Prefixes must end with a lowercase letter or number and be 16 or fewer chara
No, we only enforce that in the first member of the stack (which is Account Infrastructure Base) as that is the earliest we can catch it. I don't think we need to enforce this in the COS instance DA when its not actually needed

2025-02-17 17:00 UTC, ocofaigh commented on solutions/instance/variables.tf
> +    error_message = "Prefix must begin with a lowercase letter, contain only lowercase letters, numbers, and - characters. Prefixes must end with a lowercase letter or number and be 16 or fewer chara
Hmm but might be worth deep diving on as the Core security services stack doesn't actually call Account Infrastructure Base

2025-04-09 17:44 UTC, kierramarie commented
/run pipeline

2025-04-25 11:44 UTC, ocofaigh commented
@kierramarie There is no code changes in this PR - is this PR applicable anymore?

2025-04-25 14:24 UTC, kierramarie commented
@ocofaigh hmm I guess not. I will close it.

2025-04-25 14:24 UTC, closed without merging